apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
    field.cattle.io/description: Moonwalk Mission fun
  name: bixi-life-ingress
  namespace: bixi-life
spec:
  rules:
  - host: bixi.life
    http:
      paths:
      - backend:
          serviceName: bixi-life-service
          servicePort: 80
        path: /
        pathType: Prefix
  - host: www.bixi.life
    http:
      paths:
      - backend:
          serviceName: bixi-life-service
          servicePort: 80
        path: /
        pathType: Prefix
  - host: bixi.paulynomial.com
    http:
      paths:
      - backend:
          serviceName: bixi-life-service
          servicePort: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bixi.life
    - bixi.paulynomial.com
    secretName: bixi-ingress-prod-tls
